import sys

import numpy as np
import yaml
from PIL import Image

# Gazebo world from an occupancy map: the occupied cells become walls, in the map frame.
# usage: python3 scripts/map_to_world.py <map without extension> <world.sdf>
HEIGHT = 0.5    # m, well above the lidar plane (0.16 m)


def wall_boxes(occupied):
    # runs of occupied cells in each row, then identical runs in consecutive rows merged
    boxes, open_runs = [], {}
    for row in range(occupied.shape[0] + 1):
        runs = set()
        if row < occupied.shape[0]:
            cells = np.flatnonzero(occupied[row])
            if len(cells):
                breaks = np.flatnonzero(np.diff(cells) > 1)
                starts = np.r_[cells[0], cells[breaks + 1]]
                ends = np.r_[cells[breaks], cells[-1]]
                runs = set(zip(starts.tolist(), ends.tolist()))
        for run in list(open_runs):
            if run not in runs:
                boxes.append((open_runs.pop(run), row - 1, *run))    # first row, last row, first col, last col
        for run in runs:
            open_runs.setdefault(run, row)
    return boxes


def main(map_path, world_path):
    meta = yaml.safe_load(open(map_path + '.yaml'))
    img = np.array(Image.open(map_path + '.pgm'))
    res, (x0, y0) = meta['resolution'], meta['origin'][:2]
    h = img.shape[0]
    boxes = wall_boxes(img < 50)

    walls = []
    for r0, r1, c0, c1 in boxes:
        sx, sy = (c1 - c0 + 1) * res, (r1 - r0 + 1) * res
        cx = x0 + (c0 + c1 + 1) / 2 * res
        cy = y0 + (h - (r0 + r1 + 1) / 2) * res       # image rows go down, y goes up
        geometry = f'<geometry><box><size>{sx:.3f} {sy:.3f} {HEIGHT}</size></box></geometry>'
        walls.append(f'''        <collision name="c{len(walls)}"><pose>{cx:.3f} {cy:.3f} {HEIGHT / 2} 0 0 0</pose>{geometry}</collision>
        <visual name="v{len(walls)}"><pose>{cx:.3f} {cy:.3f} {HEIGHT / 2} 0 0 0</pose>{geometry}</visual>''')

    open(world_path, 'w').write(f'''<?xml version="1.0"?>
<!-- generated by scripts/map_to_world.py from {map_path}: {len(boxes)} wall boxes -->
<sdf version="1.9">
  <world name="room">
    <!-- nothing here falls: the car has no collisions and its dynamics plugin moves it -->
    <gravity>0 0 0</gravity>
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <light type="directional" name="sun">
      <pose>0 0 10 0 0 0</pose>
      <direction>-0.3 0.2 -1</direction>
      <diffuse>0.9 0.9 0.9 1</diffuse>
    </light>
    <model name="ground">
      <static>true</static>
      <link name="link">
        <collision name="c"><geometry><plane><normal>0 0 1</normal><size>30 30</size></plane></geometry></collision>
        <visual name="v"><geometry><plane><normal>0 0 1</normal><size>30 30</size></plane></geometry></visual>
      </link>
    </model>
    <model name="walls">
      <static>true</static>
      <link name="link">
{chr(10).join(walls)}
      </link>
    </model>
  </world>
</sdf>
''')
    print(f'{len(boxes)} wall boxes from {int((img < 50).sum())} occupied cells -> {world_path}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
